### PR TITLE
Fix dbnav time zone bug

### LINKED ISSUE #24: `dbnav` / `journeys()`: incorrect timezone for starting/ending walks [upstream]
I noticed some incredibly annoying behavior of the `dbnav` profile for journeys starting with a walk: The `departure` and `arrival` of the starting walk are offset by one hour sometimes. One example is the last journey from this request: `http://localhost:3000/journeys?from.type=location,from.id=991671997&from.address=Berlin%20Fernsehturm%20(Tourismus)&from.latitude=52.5213&from.longitude=13.409694&to=8011160&results=10&departure=2025-03-04T10%3A08%3A00.000Z`:
<details>
<summary>parsed response</summary>

```json
{
	"earlierRef": "3|OB|MTµ14µ117305µ117305µ117314µ117314µ0µ0µ165µ117305µ1µ0µ1050µ0µ0µ-2147483648µ1µ2|PDHµc9198a0b6ad0ca1c96b4f7723ab4263d|RDµ4032025|RTµ110800|USµ0|RSµINIT",
	"laterRef": "3|OF|MTµ14µ117315µ117315µ117324µ117324µ0µ0µ165µ117311µ5µ0µ1050µ0µ0µ-2147483648µ1µ2|PDHµc9198a0b6ad0ca1c96b4f7723ab4263d|RDµ4032025|RTµ110800|USµ0|RSµINIT",
	"journeys": [
		{
			"type": "journey",
			"legs": [
				{
					"origin": {
						"type": "location",
						"id": null,
						"latitude": 52.5213,
						"longitude": 13.409694,
						"name": "Berlin Fernsehturm (Tourismus)",
						"address": "Berlin Fernsehturm (Tourismus)"
					},
					"destination": {
						"type": "station",
						"id": "8089001",
						"name": "Berlin Alexanderplatz (S)",
						"location": {
							"type": "location",
							"id": "8089001",
							"latitude": 52.521645,
							"longitude": 13.411097
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 3366,
						"weight": 178.45
					},
					"departure": "2025-03-04T11:05:00+01:00",
					"plannedDeparture": "2025-03-04T11:05:00+01:00",
					"departureDelay": null,
					"arrival": "2025-03-04T11:08:00+01:00",
					"plannedArrival": "2025-03-04T11:08:00+01:00",
					"arrivalDelay": null,
					"public": true,
					"walking": true,
					"distance": 148
				},
				{
					"origin": {
						"type": "station",
						"id": "8089001",
						"name": "Berlin Alexanderplatz (S)",
						"location": {
							"type": "location",
							"id": "8089001",
							"latitude": 52.521645,
							"longitude": 13.411097
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 3366,
						"weight": 178.45
					},
					"destination": {
						"type": "station",
						"id": "8089021",
						"name": "Berlin Hbf (S-Bahn)",
						"location": {
							"type": "location",
							"id": "8089021",
							"latitude": 52.525166,
							"longitude": 13.369279
						},
						"products": {
							"nationalExpress": true,
							"national": true,
							"regionalExp": true,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 2919,
						"weight": 113
					},
					"departure": "2025-03-04T11:08:00+01:00",
					"plannedDeparture": "2025-03-04T11:08:00+01:00",
					"departureDelay": null,
					"arrival": "2025-03-04T11:14:00+01:00",
					"plannedArrival": "2025-03-04T11:14:00+01:00",
					"arrivalDelay": null,
					"tripId": "2|#VN#1#ST#1740599313#PI#0#ZI#329522#TA#1#DA#40325#1S#8013064#1T#1010#LS#8089330#LT#1134#PU#80#RT#1#CA#s#ZE#5#ZB#S      5#PC#4#FR#8013064#FT#1010#TO#8089330#TT#1134#",
					"line": {
						"type": "line",
						"id": "s-5064",
						"fahrtNr": "5064",
						"name": "S 5",
						"public": true,
						"adminCode": "08____",
						"productName": "S",
						"mode": "train",
						"product": "suburban",
						"operator": {
							"type": "operator",
							"id": "s-bahn-berlin",
							"name": "S-Bahn Berlin"
						}
					},
					"direction": "Berlin Olympiastadion",
					"arrivalPlatform": "16",
					"plannedArrivalPlatform": "16",
					"departurePlatform": "4",
					"plannedDeparturePlatform": "4",
					"remarks": [
						{
							"text": "Number of bicycles conveyed limited",
							"type": "hint",
							"code": "bicycle-conveyance",
							"summary": "bicycles conveyed"
						},
						{
							"text": "2nd class only",
							"type": "hint",
							"code": "2nd-class-only",
							"summary": "2. class only"
						}
					]
				}
			],
			"refreshToken": "¶HKI¶G@F$A=2@O=Berlin Fernsehturm (Tourismus)@X=13409694@Y=52521300@a=128@$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=608089001@a=128@$202503041105$202503041107$$$1$$$$$$§W$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=608089001@a=128@$A=1@O=Berlin Alexanderplatz (S)@X=13411007@Y=52521643@L=8089001@a=128@$202503041107$202503041108$$$1$$$$$$§T$A=1@O=Berlin Alexanderplatz (S)@X=13411007@Y=52521643@L=8089001@a=128@$A=1@O=Berlin Hbf (S-Bahn)@X=13369549@Y=52525589@L=8089021@a=128@$202503041108$202503041114$S      5$$1$$$$$$¶GP¶ft@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§bt@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§tf@$f@$f@$f@$f@$f@$",
			"remarks": []
		},
		{
			"type": "journey",
			"legs": [
				{
					"origin": {
						"type": "location",
						"id": null,
						"latitude": 52.5213,
						"longitude": 13.409694,
						"name": "Berlin Fernsehturm (Tourismus)",
						"address": "Berlin Fernsehturm (Tourismus)"
					},
					"destination": {
						"type": "station",
						"id": "8089001",
						"name": "Berlin Alexanderplatz (S)",
						"location": {
							"type": "location",
							"id": "8089001",
							"latitude": 52.521645,
							"longitude": 13.411097
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 3366,
						"weight": 178.45
					},
					"departure": "2025-03-04T11:07:00+01:00",
					"plannedDeparture": "2025-03-04T11:07:00+01:00",
					"departureDelay": null,
					"arrival": "2025-03-04T11:10:00+01:00",
					"plannedArrival": "2025-03-04T11:10:00+01:00",
					"arrivalDelay": null,
					"public": true,
					"walking": true,
					"distance": 148
				},
				{
					"origin": {
						"type": "station",
						"id": "8089001",
						"name": "Berlin Alexanderplatz (S)",
						"location": {
							"type": "location",
							"id": "8089001",
							"latitude": 52.521645,
							"longitude": 13.411097
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 3366,
						"weight": 178.45
					},
					"destination": {
						"type": "station",
						"id": "8089021",
						"name": "Berlin Hbf (S-Bahn)",
						"location": {
							"type": "location",
							"id": "8089021",
							"latitude": 52.525166,
							"longitude": 13.369279
						},
						"products": {
							"nationalExpress": true,
							"national": true,
							"regionalExp": true,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 2919,
						"weight": 113
					},
					"departure": "2025-03-04T11:11:00+01:00",
					"plannedDeparture": "2025-03-04T11:10:00+01:00",
					"departureDelay": 60,
					"arrival": "2025-03-04T11:17:00+01:00",
					"plannedArrival": "2025-03-04T11:16:00+01:00",
					"arrivalDelay": 60,
					"tripId": "2|#VN#1#ST#1740599313#PI#0#ZI#329988#TA#11#DA#40325#1S#8089188#1T#1041#LS#8089184#LT#1152#PU#80#RT#1#CA#s#ZE#7#ZB#S      7#PC#4#FR#8089188#FT#1041#TO#8089184#TT#1152#",
					"line": {
						"type": "line",
						"id": "s-7548",
						"fahrtNr": "7548",
						"name": "S 7",
						"public": true,
						"adminCode": "08____",
						"productName": "S",
						"mode": "train",
						"product": "suburban",
						"operator": {
							"type": "operator",
							"id": "s-bahn-berlin",
							"name": "S-Bahn Berlin"
						}
					},
					"direction": "Potsdam Hbf (S)",
					"arrivalPlatform": "16",
					"plannedArrivalPlatform": "16",
					"departurePlatform": "4",
					"plannedDeparturePlatform": "4",
					"remarks": [
						{
							"text": "Number of bicycles conveyed limited",
							"type": "hint",
							"code": "bicycle-conveyance",
							"summary": "bicycles conveyed"
						},
						{
							"text": "2nd class only",
							"type": "hint",
							"code": "2nd-class-only",
							"summary": "2. class only"
						}
					]
				}
			],
			"refreshToken": "¶HKI¶G@F$A=2@O=Berlin Fernsehturm (Tourismus)@X=13409694@Y=52521300@a=128@$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=608089001@a=128@$202503041107$202503041109$$$1$$$$$$§W$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=608089001@a=128@$A=1@O=Berlin Alexanderplatz (S)@X=13411007@Y=52521643@L=8089001@a=128@$202503041109$202503041110$$$1$$$$$$§T$A=1@O=Berlin Alexanderplatz (S)@X=13411007@Y=52521643@L=8089001@a=128@$A=1@O=Berlin Hbf (S-Bahn)@X=13369549@Y=52525589@L=8089021@a=128@$202503041110$202503041116$S      7$$3$$$$$$¶GP¶ft@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§bt@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§tf@$f@$f@$f@$f@$f@$",
			"remarks": []
		},
		{
			"type": "journey",
			"legs": [
				{
					"origin": {
						"type": "location",
						"id": null,
						"latitude": 52.5213,
						"longitude": 13.409694,
						"name": "Berlin Fernsehturm (Tourismus)",
						"address": "Berlin Fernsehturm (Tourismus)"
					},
					"destination": {
						"type": "station",
						"id": "8011155",
						"name": "Berlin Alexanderplatz",
						"location": {
							"type": "location",
							"id": "8011155",
							"latitude": 52.521526,
							"longitude": 13.411088
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"weight": 178.45
					},
					"departure": "2025-03-04T11:08:00+01:00",
					"plannedDeparture": "2025-03-04T11:08:00+01:00",
					"departureDelay": null,
					"arrival": "2025-03-04T11:10:00+01:00",
					"plannedArrival": "2025-03-04T11:10:00+01:00",
					"arrivalDelay": null,
					"public": true,
					"walking": true,
					"distance": 137
				},
				{
					"origin": {
						"type": "station",
						"id": "8011155",
						"name": "Berlin Alexanderplatz",
						"location": {
							"type": "location",
							"id": "8011155",
							"latitude": 52.521526,
							"longitude": 13.411088
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"weight": 178.45
					},
					"destination": {
						"type": "station",
						"id": "8011160",
						"name": "Berlin Hbf",
						"location": {
							"type": "location",
							"id": "8011160",
							"latitude": 52.524925,
							"longitude": 13.369629
						},
						"products": {
							"nationalExpress": true,
							"national": true,
							"regionalExp": true,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"weight": 113
					},
					"departure": "2025-03-04T11:12:00+01:00",
					"plannedDeparture": "2025-03-04T11:11:00+01:00",
					"departureDelay": 60,
					"arrival": "2025-03-04T11:18:00+01:00",
					"plannedArrival": "2025-03-04T11:18:00+01:00",
					"arrivalDelay": 0,
					"tripId": "2|#VN#1#ST#1740599313#PI#0#ZI#534608#TA#1#DA#40325#1S#8011201#1T#1044#LS#8010381#LT#1437#PU#80#RT#1#CA#DPN#ZE#62015#ZB#RE 62015#PC#3#FR#8011201#FT#1044#TO#8010381#TT#1437#",
					"line": {
						"type": "line",
						"id": "re-62015",
						"fahrtNr": "62015",
						"name": "RE 8",
						"public": true,
						"adminCode": "OWRE__",
						"productName": "RE",
						"mode": "train",
						"product": "regional",
						"operator": {
							"type": "operator",
							"id": "ostdeutsche-eisenbahn-gmbh",
							"name": "Ostdeutsche Eisenbahn GmbH"
						}
					},
					"direction": "Wismar",
					"arrivalPlatform": "14",
					"plannedArrivalPlatform": "14",
					"departurePlatform": "2",
					"plannedDeparturePlatform": "2",
					"remarks": [
						{
							"text": "Number of bicycles conveyed limited",
							"type": "hint",
							"code": "bicycle-conveyance",
							"summary": "bicycles conveyed"
						},
						{
							"code": "GL",
							"summary": "Conveyance of groups is limited",
							"text": "Conveyance of groups is limited",
							"type": "hint",
							"priority": 330
						},
						{
							"text": "space for wheelchairs",
							"type": "hint",
							"code": "wheelchairs-space",
							"summary": "space for wheelchairs"
						},
						{
							"text": "vehicle-mounted access aid",
							"type": "hint",
							"code": "boarding-ramp",
							"summary": "vehicle-mounted boarding ramp available"
						},
						{
							"code": "EA",
							"summary": "Behindertengerechte Ausstattung",
							"text": "Behindertengerechte Ausstattung",
							"type": "hint",
							"priority": 560
						},
						{
							"text": "power sockets for laptop",
							"type": "hint",
							"code": "power-sockets",
							"summary": "power sockets available"
						},
						{
							"text": "air conditioning",
							"type": "hint",
							"code": "air-conditioned",
							"summary": "air-conditioned vehicle"
						},
						{
							"text": "Wifi available",
							"type": "hint",
							"code": "wifi",
							"summary": "WiFi available"
						}
					]
				}
			],
			"refreshToken": "¶HKI¶G@F$A=2@O=Berlin Fernsehturm (Tourismus)@X=13409694@Y=52521300@a=128@$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=618011155@a=128@$202503041108$202503041110$$$1$$$$$$§W$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=618011155@a=128@$A=1@O=Berlin Alexanderplatz@X=13410962@Y=52521481@L=8011155@a=128@$202503041110$202503041110$$$1$$$$$$§T$A=1@O=Berlin Alexanderplatz@X=13410962@Y=52521481@L=8011155@a=128@$A=1@O=Berlin Hbf@X=13369549@Y=52525589@L=8011160@a=128@$202503041111$202503041118$RE 62015$$1$$$$$$¶GP¶ft@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§bt@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§tf@$f@$f@$f@$f@$f@$",
			"remarks": []
		},
		{
			"type": "journey",
			"legs": [
				{
					"origin": {
						"type": "location",
						"id": null,
						"latitude": 52.5213,
						"longitude": 13.409694,
						"name": "Berlin Fernsehturm (Tourismus)",
						"address": "Berlin Fernsehturm (Tourismus)"
					},
					"destination": {
						"type": "station",
						"id": "8089001",
						"name": "Berlin Alexanderplatz (S)",
						"location": {
							"type": "location",
							"id": "8089001",
							"latitude": 52.521645,
							"longitude": 13.411097
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 3366,
						"weight": 178.45
					},
					"departure": "2025-03-04T11:10:00+01:00",
					"plannedDeparture": "2025-03-04T11:10:00+01:00",
					"departureDelay": null,
					"arrival": "2025-03-04T11:13:00+01:00",
					"plannedArrival": "2025-03-04T11:13:00+01:00",
					"arrivalDelay": null,
					"public": true,
					"walking": true,
					"distance": 148
				},
				{
					"origin": {
						"type": "station",
						"id": "8089001",
						"name": "Berlin Alexanderplatz (S)",
						"location": {
							"type": "location",
							"id": "8089001",
							"latitude": 52.521645,
							"longitude": 13.411097
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 3366,
						"weight": 178.45
					},
					"destination": {
						"type": "station",
						"id": "8089021",
						"name": "Berlin Hbf (S-Bahn)",
						"location": {
							"type": "location",
							"id": "8089021",
							"latitude": 52.525166,
							"longitude": 13.369279
						},
						"products": {
							"nationalExpress": true,
							"national": true,
							"regionalExp": true,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 2919,
						"weight": 113
					},
					"departure": "2025-03-04T11:13:00+01:00",
					"plannedDeparture": "2025-03-04T11:13:00+01:00",
					"departureDelay": null,
					"arrival": "2025-03-04T11:19:00+01:00",
					"plannedArrival": "2025-03-04T11:19:00+01:00",
					"arrivalDelay": null,
					"tripId": "2|#VN#1#ST#1740599313#PI#0#ZI#330796#TA#3#DA#40325#1S#8089201#1T#1029#LS#8089083#LT#1146#PU#80#RT#1#CA#s#ZE#9#ZB#S      9#PC#4#FR#8089201#FT#1029#TO#8089083#TT#1146#",
					"line": {
						"type": "line",
						"id": "s-9070",
						"fahrtNr": "9070",
						"name": "S 9",
						"public": true,
						"adminCode": "08____",
						"productName": "S",
						"mode": "train",
						"product": "suburban",
						"operator": {
							"type": "operator",
							"id": "s-bahn-berlin",
							"name": "S-Bahn Berlin"
						}
					},
					"direction": "Berlin-Spandau (S)",
					"arrivalPlatform": "16",
					"plannedArrivalPlatform": "16",
					"departurePlatform": "4",
					"plannedDeparturePlatform": "4",
					"remarks": [
						{
							"text": "Number of bicycles conveyed limited",
							"type": "hint",
							"code": "bicycle-conveyance",
							"summary": "bicycles conveyed"
						},
						{
							"text": "2nd class only",
							"type": "hint",
							"code": "2nd-class-only",
							"summary": "2. class only"
						}
					]
				}
			],
			"refreshToken": "¶HKI¶G@F$A=2@O=Berlin Fernsehturm (Tourismus)@X=13409694@Y=52521300@a=128@$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=608089001@a=128@$202503041110$202503041112$$$1$$$$$$§W$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=608089001@a=128@$A=1@O=Berlin Alexanderplatz (S)@X=13411007@Y=52521643@L=8089001@a=128@$202503041112$202503041113$$$1$$$$$$§T$A=1@O=Berlin Alexanderplatz (S)@X=13411007@Y=52521643@L=8089001@a=128@$A=1@O=Berlin Hbf (S-Bahn)@X=13369549@Y=52525589@L=8089021@a=128@$202503041113$202503041119$S      9$$1$$$$$$¶GP¶ft@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§bt@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§tf@$f@$f@$f@$f@$f@$",
			"remarks": []
		},
		{
			"type": "journey",
			"legs": [
				{
					"origin": {
						"type": "location",
						"id": null,
						"latitude": 52.5213,
						"longitude": 13.409694,
						"name": "Berlin Fernsehturm (Tourismus)",
						"address": "Berlin Fernsehturm (Tourismus)"
					},
					"destination": {
						"type": "station",
						"id": "8089001",
						"name": "Berlin Alexanderplatz (S)",
						"location": {
							"type": "location",
							"id": "8089001",
							"latitude": 52.521645,
							"longitude": 13.411097
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 3366,
						"weight": 178.45
					},
					"departure": "2025-03-04T11:15:00+01:00",
					"plannedDeparture": "2025-03-04T11:15:00+01:00",
					"departureDelay": null,
					"arrival": "2025-03-04T11:18:00+01:00",
					"plannedArrival": "2025-03-04T11:18:00+01:00",
					"arrivalDelay": null,
					"public": true,
					"walking": true,
					"distance": 148
				},
				{
					"origin": {
						"type": "station",
						"id": "8089001",
						"name": "Berlin Alexanderplatz (S)",
						"location": {
							"type": "location",
							"id": "8089001",
							"latitude": 52.521645,
							"longitude": 13.411097
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 3366,
						"weight": 178.45
					},
					"destination": {
						"type": "station",
						"id": "8089021",
						"name": "Berlin Hbf (S-Bahn)",
						"location": {
							"type": "location",
							"id": "8089021",
							"latitude": 52.525166,
							"longitude": 13.369279
						},
						"products": {
							"nationalExpress": true,
							"national": true,
							"regionalExp": true,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"distance": 2919,
						"weight": 113
					},
					"departure": "2025-03-04T11:18:00+01:00",
					"plannedDeparture": "2025-03-04T11:18:00+01:00",
					"departureDelay": null,
					"arrival": "2025-03-04T11:24:00+01:00",
					"plannedArrival": "2025-03-04T11:24:00+01:00",
					"arrivalDelay": null,
					"tripId": "2|#VN#1#ST#1740599313#PI#0#ZI#329767#TA#2#DA#40325#1S#8089072#1T#1051#LS#8089330#LT#1144#PU#80#RT#1#CA#s#ZE#5#ZB#S      5#PC#4#FR#8089072#FT#1051#TO#8089330#TT#1144#",
					"line": {
						"type": "line",
						"id": "s-5554",
						"fahrtNr": "5554",
						"name": "S 5",
						"public": true,
						"adminCode": "08____",
						"productName": "S",
						"mode": "train",
						"product": "suburban",
						"operator": {
							"type": "operator",
							"id": "s-bahn-berlin",
							"name": "S-Bahn Berlin"
						}
					},
					"direction": "Berlin Olympiastadion",
					"arrivalPlatform": "16",
					"plannedArrivalPlatform": "16",
					"departurePlatform": "4",
					"plannedDeparturePlatform": "4",
					"remarks": [
						{
							"text": "Number of bicycles conveyed limited",
							"type": "hint",
							"code": "bicycle-conveyance",
							"summary": "bicycles conveyed"
						},
						{
							"text": "2nd class only",
							"type": "hint",
							"code": "2nd-class-only",
							"summary": "2. class only"
						}
					]
				}
			],
			"refreshToken": "¶HKI¶G@F$A=2@O=Berlin Fernsehturm (Tourismus)@X=13409694@Y=52521300@a=128@$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=608089001@a=128@$202503041115$202503041117$$$1$$$$$$§W$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=608089001@a=128@$A=1@O=Berlin Alexanderplatz (S)@X=13411007@Y=52521643@L=8089001@a=128@$202503041117$202503041118$$$1$$$$$$§T$A=1@O=Berlin Alexanderplatz (S)@X=13411007@Y=52521643@L=8089001@a=128@$A=1@O=Berlin Hbf (S-Bahn)@X=13369549@Y=52525589@L=8089021@a=128@$202503041118$202503041124$S      5$$1$$$$$$¶GP¶ft@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§bt@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§tf@$f@$f@$f@$f@$f@$",
			"remarks": []
		},
		{
			"type": "journey",
			"legs": [
				{
					"origin": {
						"type": "location",
						"id": null,
						"latitude": 52.5213,
						"longitude": 13.409694,
						"name": "Berlin Fernsehturm (Tourismus)",
						"address": "Berlin Fernsehturm (Tourismus)"
					},
					"destination": {
						"type": "station",
						"id": "8011155",
						"name": "Berlin Alexanderplatz",
						"location": {
							"type": "location",
							"id": "8011155",
							"latitude": 52.521526,
							"longitude": 13.411088
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"weight": 178.45
					},
					"departure": "2025-03-04T12:05:00+01:00",
					"plannedDeparture": "2025-03-04T11:03:00+01:00",
					"departureDelay": 3720,
					"arrival": "2025-03-04T12:07:00+01:00",
					"plannedArrival": "2025-03-04T11:05:00+01:00",
					"arrivalDelay": 3720,
					"public": true,
					"walking": true,
					"distance": 137
				},
				{
					"origin": {
						"type": "station",
						"id": "8011155",
						"name": "Berlin Alexanderplatz",
						"location": {
							"type": "location",
							"id": "8011155",
							"latitude": 52.521526,
							"longitude": 13.411088
						},
						"products": {
							"nationalExpress": false,
							"national": false,
							"regionalExp": false,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"weight": 178.45
					},
					"destination": {
						"type": "station",
						"id": "8011160",
						"name": "Berlin Hbf",
						"location": {
							"type": "location",
							"id": "8011160",
							"latitude": 52.524925,
							"longitude": 13.369629
						},
						"products": {
							"nationalExpress": true,
							"national": true,
							"regionalExp": true,
							"regional": true,
							"suburban": true,
							"bus": true,
							"ferry": false,
							"subway": true,
							"tram": true,
							"taxi": false
						},
						"weight": 113
					},
					"departure": "2025-03-04T11:08:00+01:00",
					"plannedDeparture": "2025-03-04T11:06:00+01:00",
					"departureDelay": 120,
					"arrival": "2025-03-04T11:13:00+01:00",
					"plannedArrival": "2025-03-04T11:12:00+01:00",
					"arrivalDelay": 60,
					"tripId": "2|#VN#1#ST#1740599313#PI#0#ZI#285771#TA#1#DA#40325#1S#8010327#1T#914#LS#8010077#LT#1253#PU#80#RT#1#CA#RE#ZE#3719#ZB#RE  3719#PC#3#FR#8010327#FT#914#TO#8010077#TT#1253#",
					"line": {
						"type": "line",
						"id": "re-3719",
						"fahrtNr": "3719",
						"name": "RE 7",
						"public": true,
						"adminCode": "800165",
						"productName": "RE",
						"mode": "train",
						"product": "regional",
						"operator": {
							"type": "operator",
							"id": "db-regio-ag-nordost",
							"name": "DB Regio AG Nordost"
						}
					},
					"direction": "Dessau Hbf",
					"arrivalPlatform": "13",
					"plannedArrivalPlatform": "13",
					"departurePlatform": "2",
					"plannedDeparturePlatform": "2",
					"remarks": [
						{
							"text": "Number of bicycles conveyed limited",
							"type": "hint",
							"code": "bicycle-conveyance",
							"summary": "bicycles conveyed"
						},
						{
							"text": "vehicle-mounted access aid",
							"type": "hint",
							"code": "boarding-ramp",
							"summary": "vehicle-mounted boarding ramp available"
						},
						{
							"text": "Wifi available",
							"type": "hint",
							"code": "wifi",
							"summary": "WiFi available"
						}
					]
				}
			],
			"refreshToken": "¶HKI¶G@F$A=2@O=Berlin Fernsehturm (Tourismus)@X=13409694@Y=52521300@a=128@$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=618011155@a=128@$202503041103$202503041105$$$1$$$$$$§W$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=618011155@a=128@$A=1@O=Berlin Alexanderplatz@X=13410962@Y=52521481@L=8011155@a=128@$202503041105$202503041105$$$1$$$$$$§T$A=1@O=Berlin Alexanderplatz@X=13410962@Y=52521481@L=8011155@a=128@$A=1@O=Berlin Hbf@X=13369549@Y=52525589@L=8011160@a=128@$202503041106$202503041112$RE  3719$$1$$$$$$¶GP¶ft@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§bt@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§tf@$f@$f@$f@$f@$f@$",
			"remarks": []
		}
	],
	"realtimeDataUpdatedAt": null
}
```

</details>

This problem seems to be caused upstream; this is the corresponding response from db vendo:
<details>

<summary>last journey of the unparsed response</summary>

```json
  {
    "verbindung": {
      "reiseDauer": 480,
      "alternative": true,
      "checksum": "f1d40d8e_3",
      "umstiegeAnzahl": 0,
      "schemaVersion": "1.23.8",
      "schemaName": "trip",
      "kontext": "¶HKI¶G@F$A=4@O=Berlin, Fernsehturm (Tourismus)@X=13409694@Y=52521301@L=991671997@a=128@$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=618011155@a=128@$202503041103$202503041105$$$1$$$$$$§W$A=1@O=Berlin Alexanderplatz@X=13410728@Y=52521409@L=618011155@a=128@$A=1@O=Berlin Alexanderplatz@X=13410962@Y=52521481@L=8011155@a=128@$202503041105$202503041105$$$1$$$$$$§T$A=1@O=Berlin Alexanderplatz@X=13410962@Y=52521481@L=8011155@a=128@$A=1@O=Berlin Hbf@X=13369549@Y=52525589@L=8011160@a=128@$202503041106$202503041112$RE  3719$$1$$$$$$¶GP¶ft@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§bt@0@2000@120@1@100@1@0@0@@@@@false@0@-1@0@-1@-1@$f@$f@$f@$f@$f@$§tf@$f@$f@$f@$f@$f@$§¶KC¶#VE#2#CF#100#CA#0#CM#0#SICT#0#AM#81#AM2#0#RT#7#¶KCC¶I1ZFIzEjRVJHIzMjSElOIzAjRUNLIzExNzMwNXwxMTczMDV8MTE3MzEzfDExNzMxM3wwfDB8MTY1fDExNzMwNXwxfDB8MTA1MHwwfDB8LTIxNDc0ODM2NDgjR0FNIzQwMzI1MTEwMyMKRiNWTiMwI1NUIzE3NDA1Nzg3NzIjUEkjMSNQVSM5MCNaSSMzMzU1NzkyMDUzI0RBIzQwMzI1I0ZSIzYxODAxMTE1NSNUTyM4MDExMTU1I0ZUIzExMDUjVFQjMTEwNSNUUyMzMSNGRiMjRlYjMCNTVCMxNzQwNTk5MzEzI1BJIzAjUFUjODAjClojVk4jMSNTVCMxNzQwNTk5MzEzI1BJIzAjWkkjMjg1NzcxI1RBIzEjREEjNDAzMjUjMVMjODAxMDMyNyMxVCM5MTQjTFMjODAxMDA3NyNMVCMxMjUzI1BVIzgwI1JUIzEjQ0EjUkUjWkUjMzcxOSNaQiNSRSAgMzcxOSNQQyMzI0ZSIzgwMTExNTUjRlQjMTEwNiNUTyM4MDExMTYwI1RUIzExMTIj¶KRCC¶#VE#1#VOLL#IST#¶SC¶1_H4sIAAAAAAACA22PW0vDQBSE/0o5Twqx7OZSm4VATENAKbaUIor4sDTbNrLJ1r0UQ8h/9yRVEPRtZ/jOzGwHZ6GBAZ3OQ/BAfFoUeTZ9yqfUR0OLD2AdNK4ugEXe8MiAEQ+Uszm3Ammf+BEJyHCO5raqB5NSMicErf2YcEM9eG/aQlq9BPbagW1PA7berHKEalUO6v5xgeLMpRsjiB9A/zaOWhwPl2BsLsVpqXaXGFmVSN4lYbpKMqFl1XiTQujGiKN1up5cbZXTlamduU6XSRzT2S2N49v0OaFBSOJZHKYvSeRHPg0ISbHc2MunirGZa/2nimLQnFBKZ/8cHITNN1tgVjsxqrWSLa4Sv6wHnNSINlOuKQ2wPZfmm+XGyMrYH1bs1JprXiPU9X3/BdwrpaSrAQAA",
      "echtzeitNotizen": [],
      "himNotizen": [],
      "auslastungsInfos": [
        {
          "klasse": "KLASSE_2",
          "stufe": 1,
          "anzeigeTextKurz": "Low demand expected"
        }
      ],
      "serviceDays": [
        {
          "letztesDatumInZeitraum": "2025-12-13",
          "planungsZeitraumAnfang": "2024-12-15",
          "planungsZeitraumEnde": "2025-12-13",
          "regular": "daily",
          "wochentage": [
            "MO",
            "DI",
            "MI",
            "DO",
            "FR",
            "SA",
            "SO"
          ]
        }
      ],
      "verbindungsAbschnitte": [
        {
          "reservierungsMeldungen": [],
          "nummer": 0,
          "abschnittsDauer": 120,
          "typ": "FUSSWEG",
          "halte": [],
          "distanz": 137,
          "himNotizen": [],
          "echtzeitNotizen": [],
          "attributNotizen": [],
          "abgangsOrt": {
            "name": "Berlin, Fernsehturm (Tourismus)",
            "locationId": "A=4@O=Berlin, Fernsehturm (Tourismus)@X=13409694@Y=52521301@U=91@L=991671997@",
            "evaNr": "991671997",
            "position": {
              "latitude": 52.5213,
              "longitude": 13.409694
            }
          },
          "abgangsDatum": "2025-03-04T11:03:00+01:00",
          "ezAbgangsDatum": "2025-03-04T11:05:00Z",
          "ankunftsOrt": {
            "name": "Berlin Alexanderplatz",
            "locationId": "A=1@O=Berlin Alexanderplatz@X=13410962@Y=52521481@U=80@L=8011155@i=U×008003135@",
            "evaNr": "8011155",
            "position": {
              "latitude": 52.521526,
              "longitude": 13.411088
            },
            "stationId": "0053"
          },
          "ankunftsDatum": "2025-03-04T11:05:00+01:00",
          "ezAnkunftsDatum": "2025-03-04T11:07:00Z",
          "produktGattung": "SONSTIGE",
          "wagenreihung": false,
          "auslastungsInfos": [
            {
              "klasse": "KLASSE_1",
              "stufe": 0,
              "anzeigeTextKurz": "No occupancy information available"
            },
            {
              "klasse": "KLASSE_2",
              "stufe": 0,
              "anzeigeTextKurz": "No occupancy information available"
            }
          ],
          "parallelZuege": []
        },
        {
          "administrationId": "800165",
          "risZuglaufId": "RE_3719",
          "risAbfahrtId": "8011155_2025-03-04T11:06:00+01:00",
          "kurztext": "RE",
          "mitteltext": "RE 7",
          "langtext": "RE 7 (3719)",
          "zuglaufId": "2|#VN#1#ST#1740599313#PI#0#ZI#285771#TA#1#DA#40325#1S#8010327#1T#914#LS#8010077#LT#1253#PU#80#RT#1#CA#RE#ZE#3719#ZB#RE  3719#PC#3#FR#8010327#FT#914#TO#8010077#TT#1253#",
          "reservierungsMeldungen": [],
          "nummer": 1,
          "abschnittsDauer": 360,
          "typ": "FAHRZEUG",
          "halte": [
            {
              "abgangsDatum": "2025-03-04T11:06:00+01:00",
              "ezAbgangsDatum": "2025-03-04T11:08:00+01:00",
              "ort": {
                "name": "Berlin Alexanderplatz",
                "locationId": "A=1@O=Berlin Alexanderplatz@X=13410962@Y=52521481@U=80@L=8011155@i=U×008003135@",
                "evaNr": "8011155",
                "position": {
                  "latitude": 52.521526,
                  "longitude": 13.411088
                },
                "stationId": "0053"
              },
              "gleis": "2",
              "attributNotizen": [],
              "echtzeitNotizen": [],
              "himNotizen": [],
              "auslastungsInfos": [
                {
                  "klasse": "KLASSE_2",
                  "stufe": 1,
                  "anzeigeTextKurz": "Low demand expected"
                }
              ]
            },
            {
              "ankunftsDatum": "2025-03-04T11:09:00+01:00",
              "abgangsDatum": "2025-03-04T11:10:00+01:00",
              "ezAbgangsDatum": "2025-03-04T11:11:00+01:00",
              "ezAnkunftsDatum": "2025-03-04T11:10:00+01:00",
              "ort": {
                "name": "Berlin Friedrichstraße",
                "locationId": "A=1@O=Berlin Friedrichstraße@X=13387203@Y=52520376@U=80@L=8011306@i=U×008003137@",
                "evaNr": "8011306",
                "position": {
                  "latitude": 52.520332,
                  "longitude": 13.386925
                },
                "stationId": "0527"
              },
              "gleis": "3",
              "attributNotizen": [],
              "echtzeitNotizen": [],
              "himNotizen": [],
              "auslastungsInfos": [
                {
                  "klasse": "KLASSE_2",
                  "stufe": 1,
                  "anzeigeTextKurz": "Low demand expected"
                }
              ]
            },
            {
              "ankunftsDatum": "2025-03-04T11:12:00+01:00",
              "ezAnkunftsDatum": "2025-03-04T11:13:00+01:00",
              "ort": {
                "name": "Berlin Hbf",
                "locationId": "A=1@O=Berlin Hbf@X=13369549@Y=52525589@U=80@L=8011160@i=U×008065969@",
                "evaNr": "8011160",
                "position": {
                  "latitude": 52.524925,
                  "longitude": 13.369629
                },
                "stationId": "1071"
              },
              "gleis": "13",
              "attributNotizen": [],
              "echtzeitNotizen": [],
              "himNotizen": [],
              "auslastungsInfos": [
                {
                  "klasse": "KLASSE_1",
                  "stufe": 0,
                  "anzeigeTextKurz": "No occupancy information available"
                },
                {
                  "klasse": "KLASSE_2",
                  "stufe": 0,
                  "anzeigeTextKurz": "No occupancy information available"
                }
              ]
            }
          ],
          "himNotizen": [],
          "echtzeitNotizen": [],
          "attributNotizen": [
            {
              "text": "Number of bicycles conveyed limited",
              "key": "FB",
              "priority": 260
            },
            {
              "text": "vehicle-mounted access aid",
              "key": "EH",
              "priority": 560
            },
            {
              "text": "Wifi available",
              "key": "WV",
              "priority": 710
            },
            {
              "text": "DB Regio AG Nordost",
              "key": "OP"
            }
          ],
          "abgangsOrt": {
            "name": "Berlin Alexanderplatz",
            "locationId": "A=1@O=Berlin Alexanderplatz@X=13410962@Y=52521481@U=80@L=8011155@i=U×008003135@",
            "evaNr": "8011155",
            "position": {
              "latitude": 52.521526,
              "longitude": 13.411088
            },
            "stationId": "0053"
          },
          "abgangsDatum": "2025-03-04T11:06:00+01:00",
          "ezAbgangsDatum": "2025-03-04T11:08:00+01:00",
          "ankunftsOrt": {
            "name": "Berlin Hbf",
            "locationId": "A=1@O=Berlin Hbf@X=13369549@Y=52525589@U=80@L=8011160@i=U×008065969@",
            "evaNr": "8011160",
            "position": {
              "latitude": 52.524925,
              "longitude": 13.369629
            },
            "stationId": "1071"
          },
          "ankunftsDatum": "2025-03-04T11:12:00+01:00",
          "ezAnkunftsDatum": "2025-03-04T11:13:00+01:00",
          "verkehrsmittelNummer": "3719",
          "richtung": "Dessau Hbf",
          "produktGattung": "RB",
          "wagenreihung": true,
          "auslastungsInfos": [
            {
              "klasse": "KLASSE_2",
              "stufe": 1,
              "anzeigeTextKurz": "Low demand expected"
            }
          ],
          "parallelZuege": []
        }
      ]
    },
    "angebote": {
      "angebotsMeldungen": [
        "Connection is in the past."
      ],
      "angebotsHinweise": [],
      "angebotsHinweisDetails": [],
      "angebotsInformationen": [],
      "reservierungsMeldungen": [],
      "alterseingabeErforderlich": false,
      "angebotseinholungNachgelagert": false,
      "angebotsCluster": [],
      "fahrradmitnahmeMoeglich": "KEINE_ANZEIGE"
    }
  }
```

</details>

Whereas `abgangsDatum` has the correct timezone `+01:00`, the timezone of `ezAbgangsDatum` is UTC.

Unfortunately, finding journeys with this problem is not simple and the requirement of real time data to be involved does not help either. ~This is some speculation, but the issue might correlate with the fact of it being an alternative journey~ (I found non-alternative journeys with this issue and alternative journeys without it, so this is not true most likely). No idea how we could deal with this. The issue is not present for `dbweb`

### PR DESCRIPTION
**Pull request by dabund24**
resolves #24

In theory, this introduces a new bug if a delay reaches across the transition from standard time to daylight saving time and vice versa (which is far less tragic than the current situation imao). That's why I decided to test for diverging time zones only in the scenarios where this bug could happen as far as we currently know (only `dbnav`; first or last leg; walk or transfer) instead of performing the checks somewhere in `parseJourneyLeg()`. I wasn't able to find this bug for transfers in the wild (yet?) as those function kind of rarely as starting or ending legs, but i guess there is a chance that this bug exists here, too.

### CODE REVIEW

**Comment by traines-source** [comment]
A nice example for a transfer as a starting leg is [this](https://github.com/public-transport/db-vendo-client/blob/a6e84be2df918c34f4f6c2225884bc6a71a4d051/docs/dumps/PCAPdroid_02_Jan_21_59_35_initial_transfer.txt): `/journeys?departure=2025-05-22T21%3A00%3A00.000%2B01%3A00&from=8000261&to=8700011`. For today the issue doesn't occur there, but I think it definitely can't harm to have the fix for transfers as well.

Thanks for your work! (And one strike for cspell :D)

File: p/dbnav/parse-journey.js [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+	}
+	if (legs.length > 1) {
+		legs[legs.length - 1] = preprocessJourneyLeg(legs.at(-1));
+	}
+
+	return parseJourneyDefault(ctx, jj);
+};
+
+const preprocessJourneyLeg = (pt) => { // fixes https://github.com/public-transport/db-vendo-client/issues/24
+	if (pt.typ === 'FUSSWEG' || pt.typ === 'TRANSFER') {
```
Comment (derhuerst) [inline p/dbnav/parse-journey.js]: @dabund24 I assume you confirmed that the problem appears with `TRANSFER` legs, too?

I'm asking because, currently, [`hafas-client`'s `mgate.exe` parsing  only covers `WALK`/`FUSSWEG` legs](https://github.com/public-transport/hafas-client/blob/3f5049d47401bec509b8caab69a1fc68086fe972/parse/journey-leg.js#L69-L78).

Comment (dabund24) [reply p/dbnav/parse-journey.js]: I haven't yet found a case for buggy transfers, but after a some trial and error I found a nice station, where it is possible to reliably get transfers.
There are hourly Regio services from Hamburg and Bremerhaven to Cuxhaven and vice versa and when replacing `Cuxhaven` with `Cuxhaven Alte Liebe (Fähre)`, the journey to the ferryport is not explicitly described (tested with the vsn profile).
So for future investigations, this would be a good place to check.

image

Comment (dabund24) [reply p/dbnav/parse-journey.js]: The instances in Paris are really interesting. Do you know if there exists a hafas profile providing realtime data for Paris? When this bug existed in db-vendo-client I don't remember it to ever happen without live data for the first/last "real" leg 🤔 (though, this is no proof that realtime data is a requirement).
